# .circleci/config.yml
version: 2.0

orbs:
    mac-permissions: circleci/macos

jobs:
  build-mac-julia-1.3:
    macos:
      xcode: 11.7.0
    working_directory: ~/SolverBenchmark.jl
    machine: true
    environment:
      JULIAVERSION: 1.3
    steps:
      - checkout
      - run: |
          # only available as a dmg for some reason
          curl -O https://julialang-s3.julialang.org/bin/mac/x64/${JULIAVERSION}/julia-${JULIAVERSION}-latest-mac64.dmg
          hdiutil mount julia-${JULIAVERSION}-latest-mac64.dmg
          sudo cp -r /Volumes/Julia-1.3.1/*.app /Applications/
          hdiutil unmount /Volumes/Julia-1.3.1
      - run: |
          /Applications/Julia-${JULIAVERSION}.app/Contents/Resources/julia/bin/julia -e 'using Pkg; Pkg.update(); Pkg.clone(pwd()); Pkg.build("SolverBenchmark"); Pkg.test("SolverBenchmark");'

  build-mac-julia-1.5:
    macos:
      xcode: 11.7.0
    working_directory: ~/SolverBenchmark.jl
    machine: true
    environment:
      JULIAVERSION: 1.5
      JULIAMINOR: 3
    steps:
      - checkout
      - run: |
          curl -O https://julialang-s3.julialang.org/bin/mac/x64/${JULIAVERSION}/julia-${JULIAVERSION}.${JULIAMINOR}-mac64.tar.gz
          tar zxf julia-${JULIAVERSION}.${JULIAMINOR}-mac64.tar.gz
      - run: |
          ./julia-${JULIAVERSION}.${JULIAMINOR}/bin/julia --code-coverage -e 'using Pkg; Pkg.update(); Pkg.activate(pwd()); Pkg.instantiate(); Pkg.build("SolverBenchmark"); Pkg.test("SolverBenchmark"; coverage=true);'
      - run: |
          ./julia-${JULIAVERSION}.${JULIAMINOR}/bin/julia -e 'using Pkg; Pkg.activate(pwd()); Pkg.instantiate(); Pkg.add("Coverage"); using Coverage; Codecov.submit(Coveralls.process_folder());'

workflows:
  version: 2
  test-bot:
    jobs:
      - build-mac-julia-1.3
      - build-mac-julia-1.5
